default:
  directories: [/home/user/Documents/, /home/baran/Pictures/]
  destination: /backup
  compression: bzip2
  exclude: ~

simple:
  directories: [/home/user/, /etc]
  destination: /home/user/backup
  compression: ~
  exclude: mp3

etc:
  directories: /etc
  destination: /backup
  compression: bzip2
  exclude: mp4

